export const projects = [
  {
  id: "cricket",
  title: "🏏 Cricket Commentary AI",

  category: "Generative AI",

  year: "2026",

  image: "/images/cricket.png",

  github:
    "https://github.com/1616piyu/Cricket-automated-commentary-R-2-1-D-Model.git",

  demo: "#",

  technologies: [
    "Python",
    "YOLOv8",
    "PyTorch",
    "OpenCV",
    "EasyOCR",
    "LLM",
  ],

  description:
    "Real-time cricket event detection and automatic commentary generation.",

  problem:
    "Cricket commentary is manually generated by commentators. There is no automated system capable of understanding cricket events from live video.",

  solution:
    "Developed an end-to-end AI pipeline that detects players, recognizes events, extracts scoreboard information using OCR, and generates natural language commentary using LLMs.",

  features: [
    "Player Detection",
    "Ball Tracking",
    "Scoreboard OCR",
    "Event Detection",
    "Natural Language Commentary",
  ],
  },

  {
    id: "fake-news",
    title: "📰 Multi-Modal Fake News Detection",

    category: "Deep Learning",
    year: "2026",

    description:
      "Deep learning model that detects fake news using both textual and visual information through NLP and Computer Vision.",
    problem:
      "Fake news spreads quickly because text-only models ignore image evidence.",
    solution:
      "Combined image and textual features using deep learning to improve fake news classification.",
    features: [
"Image Classification",
"Text Processing",
"NLP",
"ResNet50",
"Multi-modal Learning",
],

    image: "/images/fake_news.png",

    technologies: [
      "Python",
      "PyTorch",
      "NLP",
      "ResNet50",
    ],

    github:
      "https://github.com/1616piyu/multi_modal-fake-news-detection.git",

    demo: "#",
  },

  {
    id: "netflix",
    title: "🎬 Netflix Content Analysis",
    category: "Data Analytics",
    year: "2026",

    description:
      "Data analytics project that explores Netflix's content library to uncover trends using Python, SQL, Pandas, and Matplotlib.",
    problem:
      "Difficulty in identifying patterns and trends in Netflix's vast content library.",
    solution:
      "Utilized data analytics techniques to analyze viewing behavior and content performance.",
    features: [
      "Data Visualization",
      "Trend Analysis",
      "SQL Queries",
      "Pandas DataFrame Manipulation",
    ],

    image: "/images/netflix.png",

    technologies: [
      "Python",
      "Pandas",
      "SQL",
      "Matplotlib",
    ],

    github:
      "https://github.com/1616piyu/netflix-content-strategy-analysis.git",

    demo: "#",
  },

  {
    id: "mall",
    title: "🛍 Mall Customer Segmentation",

    category: "Machine Learning",
    year: "2026",

    description:
      "Implemented K-Means clustering to segment customers into groups, enabling targeted marketing and customer insights.",

    problem:
      "Difficulty in identifying customer segments and tailoring marketing strategies.",
    solution:
      "Utilized K-Means clustering to group customers based on purchasing behavior and preferences.",
    features: [
      "Customer Segmentation",
      "Clustering Analysis",
      "Data Visualization",
    ],

    image: "/images/mall.png",

    technologies: [
      "Python",
      "Scikit-learn",
      "Pandas",
      "K-Means",
    ],

    github:
      "https://github.com/1616piyu/mall-customer-segmentation.git",

    demo: "#",
  },
];